// select
let btn = document.querySelector(".btn");

// --- 
let randomNumber;
let entrance;

// this function for addEventListener
function events() {
    btn.addEventListener("click", buildNumber)
    btn.addEventListener("click", gettingInput)
}
events()

// this function for build number 1-100
function buildNumber() {
    randomNumber = Math.floor(Math.random() * 100)
    console.log(randomNumber);
}

// this function for getting input from the user
function gettingInput() {
    entrance = Number(prompt("be nazaet add chande haan?"))
    console.log(entrance);
    compare()
}

// This function is used to compare the number entered by the user and the number generated by the buildNumber function
function compare() {

    if (entrance > randomNumber) {
        console.log("Big tar az add ");
    }

    else if (entrance < randomNumber) {
        console.log("small tar az add");
    }

    else if (entrance === randomNumber) {
        console.log("barikala");
    }

}